apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":30835,"protocol":"TCP","serviceName":"plex:sonarr","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"sonarr","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"sonarr","app.kubernetes.io/version":"3.0.4.993","helm.sh/chart":"sonarr-8.2.1"},"name":"sonarr","namespace":"plex"},"spec":{"ports":[{"name":"http","port":8989,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/instance":"sonarr","app.kubernetes.io/name":"sonarr"},"type":"ClusterIP"}}
  creationTimestamp: "2021-03-05T01:27:20Z"
  labels:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/version: 3.0.4.993
    helm.sh/chart: sonarr-8.2.1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":8989,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
        f:sessionAffinity: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-05T01:27:20Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:externalTrafficPolicy: {}
        f:type: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-05T01:54:03Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2021-03-05T01:54:03Z"
  name: sonarr
  namespace: plex
  resourceVersion: "2614561"
  selfLink: /api/v1/namespaces/plex/services/sonarr
  uid: 43d2b3b9-06c4-4819-b03e-f2dc4d3e2674
spec:
  clusterIP: 10.43.203.246
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30835
    port: 8989
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
