# Default values for Sonarr.

image:
  repository: linuxserver/sonarr
  pullPolicy: IfNotPresent
  tag: version-3.0.4.993

strategy:
  type: Recreate

service:
  port:
    port: 8989

env:
  # TZ: UTC
  PUID: 0
  PGID: 0

persistence:
  config:
    enabled: true
    emptyDir: false
    storageClass: "nfs-client"
    size: 10Gi

  media:
    enabled: true
    emptyDir: false
    mountPath: /media
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    storageClass: "nfs-client"
    accessMode: ReadWriteMany
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: true
    existingClaim: "plex-data-pvc"
