apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-pvc
  labels:
    component: data
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1024Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  labels:
    component: config
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs
---
