apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":31151,"protocol":"TCP","serviceName":"plex:radarr","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"radarr","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"radarr","app.kubernetes.io/version":"3.0.0.3989","helm.sh/chart":"radarr-8.3.1"},"name":"radarr","namespace":"plex"},"spec":{"ports":[{"name":"http","port":7878,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/instance":"radarr","app.kubernetes.io/name":"radarr"},"type":"ClusterIP"}}
  creationTimestamp: "2021-03-07T01:59:31Z"
  labels:
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: radarr
    app.kubernetes.io/version: 3.0.0.3989
    helm.sh/chart: radarr-8.3.1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":7878,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
        f:sessionAffinity: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-07T01:59:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:externalTrafficPolicy: {}
        f:type: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-07T02:06:37Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2021-03-07T02:06:37Z"
  name: radarr
  namespace: plex
  resourceVersion: "3871636"
  selfLink: /api/v1/namespaces/plex/services/radarr
  uid: 4adfc15a-5e18-4b1a-a048-d53c90594048
spec:
  clusterIP: 10.43.215.95
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31151
    port: 7878
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/name: radarr
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
