# Default values for Radarr.

image:
  repository: linuxserver/radarr
  pullPolicy: IfNotPresent
  tag: version-3.0.0.3989

strategy:
  type: Recreate

service:
  port:
    port: 7878

env:
  # TZ: UTC
  PUID: 0
  PGID: 0

persistence:
  config:
    enabled: true
    emptyDir: false

  media:
    enabled: true
    emptyDir: false
    mountPath: /media
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    storageClass: "nfs-client"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    existingClaim: "plex-data-pvc"
